### PR TITLE
Auto deploy setup

### PR DESCRIPTION
**Pull request by jarrydlee**
@kwm4385 

fixes https://github.com/PagerNation/PagerNation/issues/101

### CODE REVIEW

**Comment by kwm4385** [comment]
What's up with travis failing?

**Comment by jarrydlee** [comment]
As you mentioned before, none of the tests pass at all

**Comment by jarrydlee** [comment]
The tests will need to be fixed for the auto deployment to successfully run. If none of them are useful, can we just kill them?

**Comment by kwm4385** [comment]
:dagger:

**Pull request merged**
